## Generated by ./rules.sh :
Csparse.o: Csparse.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h cs-etc.h \
 SuiteSparse/CXSparse/Include/cs.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h cholmod-etc.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
 SuiteSparse/CHOLMOD/Include/cholmod.h Csparse.h
attrib.o: attrib.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h attrib.h
bind.o: bind.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h coerce.h \
 bind.h
cholmod-common.o: cholmod-common.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h \
 cholmod-common.h cholmod-etc.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
 SuiteSparse/CHOLMOD/Include/cholmod.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h
cholmod-etc.o: cholmod-etc.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h idz.h \
 cholmod-etc.h SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
 SuiteSparse/CHOLMOD/Include/cholmod.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h
coerce.o: coerce.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h idz.h \
 coerce.h
cs-etc.o: cs-etc.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h cs-etc.h \
 SuiteSparse/CXSparse/Include/cs.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h
dense.o: dense.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h idz.h \
 dense.h
determinant.o: determinant.c \
 Mdefines.h \
 version.h \
 Msymbols.h utils.h \
 uid.h \
 cholmod-etc.h SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
 SuiteSparse/CHOLMOD/Include/cholmod.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h determinant.h
expm.o: expm.c Lapack-etc.h \
 Mdefines.h \
 version.h \
 Msymbols.h utils.h \
 uid.h expm.h
factor.o: factor.c Lapack-etc.h \
 cs-etc.h \
 SuiteSparse/CXSparse/Include/cs.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h cholmod-etc.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
 SuiteSparse/CHOLMOD/Include/cholmod.h Mdefines.h version.h \
 Msymbols.h \
 utils.h uid.h \
 factor.h
idz.o: idz.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h idz.h
init.o: init.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h Csparse.h \
 attrib.h bind.h cholmod-common.h cholmod-etc.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
 SuiteSparse/CHOLMOD/Include/cholmod.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h coerce.h dense.h \
 determinant.h expm.h factor.h kappa.h matmult.h objects.h perm.h solve.h \
 sparse.h subassign.h subscript.h tracing.h utils-R.h validity.h vector.h \
 
kappa.o: kappa.c Lapack-etc.h \
 Mdefines.h \
 version.h \
 Msymbols.h utils.h \
 uid.h kappa.h
matmult.o: matmult.c Lapack-etc.h \
 cholmod-etc.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
 SuiteSparse/CHOLMOD/Include/cholmod.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h Mdefines.h version.h \
 Msymbols.h \
 utils.h uid.h \
 idz.h coerce.h dense.h sparse.h matmult.h
objects.o: objects.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h objects.h
perm.o: perm.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h perm.h
solve.o: solve.c Lapack-etc.h \
 cs-etc.h \
 SuiteSparse/CXSparse/Include/cs.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h cholmod-etc.h \
 SuiteSparse/SuiteSparse_config/SuiteSparse_config.h \
 SuiteSparse/CHOLMOD/Include/cholmod.h Mdefines.h version.h \
 Msymbols.h \
 utils.h uid.h \
 idz.h solve.h
sparse.o: sparse.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h sparse.h
subassign.o: subassign.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h \
 subassign.h t_subassign.c
subscript.o: subscript.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h \
 subscript.h
tracing.o: tracing.c tracing.h \
 Mdefines.h version.h \
 Msymbols.h \
 utils.h uid.h
utils-R.o: utils-R.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h utils-R.h \
 t_rle.c
utils.o: utils.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h
validity.o: validity.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h \
 validity.h
vector.o: vector.c Mdefines.h version.h \
 Msymbols.h utils.h \
 uid.h vector.h
uid.o: uid.c uid.h \
 
